# -*- coding: utf-8 -*-
"""Python_Practice_QnA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gaYa9qikSSbl-ednmI_pWUlZ5iJ8mLVh

1.Write a Python program that defines a function called "add_numbers" that takes two arguments (i.e., numbers) and returns their sum. Within the function, add the two numbers together and return the result using the return statement. Call the function with the values 5 and 6, and print out the returned result. This will result in the addition of 5 and 6, with the output of the program being the sum of these two numbers.
"""

def add_numbers(num1, num2):
    return num1 + num2

result = add_numbers(5, 6)
print(result)



"""
2.Write a Python program that calculates the square root of a given number using a built-in function. Specifically, the program should take an integer or float input from the user, calculate its square root using the 'sqrt()' function from the 'math' module, and print out the result to the user. As an example, calculate the square root of the number 625 using this program, which should output the value of 25.
"""

import math

number = 625
sqrt_number = math.sqrt(number)

print("The square root of", number, "is", sqrt_number)



"""3.Write a program that prints all prime numbers between 0 to 50.


"""

for number in range(2, 51):
    is_prime = True
    for i in range(2, number):
        if number % i == 0:
            is_prime = False
            break
    if is_prime:
        print(number)



"""4. How can we swap the values of three variables (let's say a, b, and c) without using a fourth variable? For example, if we have a=5, b=8, and c=9, how can we obtain a=9, b=5, and c=8? The challenge is to perform this operation without using an additional variable to store any of the values during the swapping process.


"""

a = 5
b = 8
c = 9

a, b, c = c, a, b

print("a =", a)
print("b =", b)
print("c =", c)



"""
5. Can you write a program that determines the nature of a given number (in this case, 87) as being positive, negative, or zero? The program should be designed to take the number as input and perform the necessary calculations to determine if the number is positive (i.e., greater than zero), negative (i.e., less than zero), or zero (i.e., equal to zero). The output of the program should indicate which of these three categories the given number falls into.
"""

num = 87

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")



"""6. How can you create a program that determines whether a given number (in this case, 98) is even or odd? The program should be designed to take the number as input and perform the necessary calculations to determine whether it is divisible by two. If the number is divisible by two without leaving a remainder, it is an even number, and if there is a remainder, it is an odd number. The output of the program should indicate whether the given number is even or odd.

"""

num = 98

if num % 2 == 0:
    print("The number is even.")
else:
    print("The number is odd.")



"""7. Write a program for sum of digits.the digits are 76543 and the output should be  25.

"""

num = 76543
sum_of_digits = 0

while num > 0:
    sum_of_digits += num % 10
    num //= 10

print("The sum of digits is:", sum_of_digits)

"""8. Write a program for reversing the given number  5436 and the output  should be 6345.

"""

num = 5436
reverse = 0

while num > 0:
    # Extract the rightmost digit of the number
    digit = num % 10

    # Add the extracted digit to the reverse number
    reverse = (reverse * 10) + digit

    # Remove the rightmost digit from the number
    num //= 10

print("The reversed number is:", reverse)



"""9.Write a program to check  a given number 371 is an Armstrong number?

"""

# Function to check if a number is an Armstrong number
def is_armstrong(num):
    # Get the number of digits in the given number
    num_str = str(num)
    num_digits = len(num_str)

    # Calculate the sum of the cubes of each digit
    sum_of_cubes = sum([int(digit)**num_digits for digit in num_str])

    # Check if the sum of the cubes is equal to the original number
    if sum_of_cubes == num:
        return True
    else:
        return False

# Test the function with the number 371
num = 371
if is_armstrong(num):
    print(num, "is an Armstrong number")
else:
    print(num, "is not an Armstrong number")



"""10. Write a program the given year is 1996  a leap year.

"""

year = 1996

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")



"""11.Create a list in python using the followings: 2,3,4,5,6,7 with variable ‘a’
Add ‘mango to the above list
Also add banana, grapes & orange in the list
insert apple in the 5th position of a variable ‘a’
Remove last item from the list

"""

a = [2, 3, 4, 5, 6, 7]   # create a list with variable a
a.append('mango')       # add 'mango' to the end of the list
a.extend(['banana', 'grapes', 'orange'])  # add multiple items to the end of the list
a.insert(4, 'apple')    # insert 'apple' at the 5th position (index 4) of the list
a.pop()                 # remove and return the last item from the list

print(a)                # print the modified list

"""12.
L = [1,2,3,4,5,6,7]
Using the above list slice from 1:4

"""

L = [1, 2, 3, 4, 5, 6, 7]   # create a list L
sliced_L = L[1:4]          # slice the list from index 1 to index 3 (excluding index 4)

print(sliced_L)            # print the sliced list

"""13.Reverse the order of given string L = [4,5,6,8,3]"""

L = [4, 5, 6, 8, 3]   # create a list L
L.reverse()           # reverse the order of the list using the reverse() method

print(L)              # print the reversed list

"""14.Use list comprehension to square the given list L=[2,4,7,3,6,8]"""

L = [2, 4, 7, 3, 6, 8]   # create a list L
squared_L = [x**2 for x in L]   # use list comprehension to square the elements of L

print(squared_L)       # print the squared list

"""15.Create a function that takes in a tuple of integers and returns the sum of the integers. Test the function with a tuple of your choice.

"""

def sum_tuple(t):
    """
    Takes a tuple of integers and returns the sum of its elements.
    """
    return sum(t)

# Test the function with a tuple of integers
my_tuple = (3, 5, 7, 9)
print(sum_tuple(my_tuple))

"""16.Create two sets of your favorite fruits, and use the union() method to combine them into a single set. Print the resulting set to the console.

"""

# Create two sets of favorite fruits
set1 = {"apple", "banana", "orange"}
set2 = {"mango", "pineapple", "kiwi"}

# Combine the two sets into a single set using the union() method
combined_set = set1.union(set2)

# Print the resulting set
print(combined_set)

"""17.Create a set of random words, and use the add() method to add a new word to the set. Print the resulting set to the console.

"""

# Create a set of random words
my_set = {"apple", "banana", "cherry"}

# Add a new word to the set using the add() method
my_set.add("orange")

# Print the resulting set
print(my_set)

"""18.Create a set of your favorite animals, and use the remove() method to remove one animal from the set. Print the resulting set to the console.

"""

# Create a set of favorite animals
my_set = {"lion", "tiger", "bear", "elephant"}

# Remove one animal from the set using the remove() method
my_set.remove("bear")

# Print the resulting set
print(my_set)

"""19.favorite_books = {"1984", "To Kill a Mockingbird", "Pride and Prejudice"}
      favorite_movies = ["The Shawshank Redemption", "The Godfather", "The Dark Knight"]
      Use the zip() function to combine the book set and movie list into a list of tuples representing book/movie pairs.
      Print the resulting list.

"""

# Create a set of favorite books and a list of favorite movies
favorite_books = {"1984", "To Kill a Mockingbird", "Pride and Prejudice"}
favorite_movies = ["The Shawshank Redemption", "The Godfather", "The Dark Knight"]

# Combine the book set and movie list into a list of tuples using the zip() function
book_movie_pairs = list(zip(favorite_books, favorite_movies))

# Print the resulting list
print(book_movie_pairs)

"""20.Write a Python program to find the difference between consecutive numbers in a

1.   List item
2.   List item

list.

"""

def consecutive_difference(lst):
    diff_lst = []
    for i in range(len(lst)-1):
        diff_lst.append(abs(lst[i] - lst[i+1]))
    return diff_lst

# Example usage
my_list = [3, 5, 2, 8, 1]
diff_list = consecutive_difference(my_list)
print(diff_list)

#note:The consecutive_difference() function takes a list as input and returns a list of differences between consecutive numbers

"""21.Create a dictionary called fruits with the following key-value pairs:
"apple": 0.75
"banana": 1.25
"orange": 0.90
Then, print out the price of a banana.

"""

# Create a dictionary called fruits with the given key-value pairs
fruits = {
    "apple": 0.75,
    "banana": 1.25,
    "orange": 0.90
}

# Print out the price of a banana
print(fruits["banana"])

"""22.Create an empty dictionary called ages. Add the following key-value pairs to the dictionary:
"Alice": 30
"Bob": 25
"Charlie": 35
Then, print out the age of Charlie.
"""

# Create an empty dictionary called ages
ages = {}

# Add the given key-value pairs to the dictionary
ages["Alice"] = 30
ages["Bob"] = 25
ages["Charlie"] = 35

# Print out the age of Charlie
print(ages["Charlie"])

"""23.Write a function called word_count(text) that takes a string as input and returns a dictionary where each key is a word in the text and its value is the number of times that word appears in the text. For example, word_count("hello world hello") should return {"hello": 2, "world": 1}."""

def word_count(text):
    # Convert the input string to lowercase and split into words
    words = text.lower().split()
    # Initialize an empty dictionary
    counts = {}
    # Loop through the words and count the number of occurrences of each word
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    # Return the resulting dictionary
    return counts

# Example usage
text = "hello world hello"
counts = word_count(text)
print(counts)

"""24.Create a dictionary called phone_book with the following key-value pairs:
"Alice": "555-1234"
"Bob": "555-5678"
"Charlie": "555-9012"
Then, prompt the user to enter a name and print out the corresponding phone number. If the name is not in the phone book, print out a message saying that the name was not found.


"""

# create phone_book dictionary
phone_book = {
    "Alice": "555-1234",
    "Bob": "555-5678",
    "Charlie": "555-9012"
}

# prompt user to enter a name
name = input("Enter a name to lookup in the phone book: ")

# lookup phone number by name
if name in phone_book:
    phone_number = phone_book[name]
    print(f"{name}'s phone number is {phone_number}.")
else:
    print(f"{name} was not found in the phone book.")

"""25.Write a program that prompts the user to enter a number between 1 and 10. If the number is less than 5, print out "Too low!", otherwise print out "Too high!".

"""

# prompt user to enter a number between 1 and 10
number = int(input("Enter a number between 1 and 10: "))

# check if number is less than 5
if number < 5:
    print("Too low!")
else:
    print("Too high!")

"""26.Write a program that prompts the user to enter a password. If the password is "password123", print out "Access granted", otherwise print out "Access denied".

"""

# prompt user to enter a password
password = input("Enter a password: ")

# check if password is correct
if password == "password123":
    print("Access granted")
else:
    print("Access denied")

"""27.Write a program that prompts the user to enter a positive integer. Then, use a loop to print out all the odd numbers from 1 to that integer.

"""

# Using for loop
# prompt user to enter a positive integer
num = int(input("Enter a positive integer: "))

# print out all the odd numbers from 1 to num
for i in range(1, num+1, 2):
    print(i)

# Using while loop
# prompt user to enter a positive integer
num = int(input("Enter a positive integer: "))

# initialize counter to 1
i = 1

# print out all the odd numbers from 1 to num
while i <= num:
    print(i)
    i += 2

"""28.Write a program that generates a random number between 1 and 100 and then prompts the user to guess the number. If the user's guess is too low, print out "Too low!", if the guess is too high, print out "Too high!", and if the guess is correct, print out "You win!".

"""

import random

# generate a random number between 1 and 100
secret_number = random.randint(1, 100)

# prompt user to guess the number
guess = int(input("Guess the number between 1 and 100: "))

# check if guess is too low, too high, or correct
while guess != secret_number:
    if guess < secret_number:
        print("Too low!")
    else:
        print("Too high!")
    guess = int(input("Guess again: "))

# guess is correct, print "You win!"
print("You win!")

"""29.Write a program that generates a random number between 1 and 10 and then prompts the user to guess the number. The user has three attempts to guess the number. If the user guesses correctly within three attempts, print out "You win!", otherwise print out "You lose!".

"""

import random

# generate a random number between 1 and 10
secret_number = random.randint(1, 10)

# set number of attempts to 3
attempts = 3

# prompt user to guess the number
while attempts > 0:
    guess = int(input("Guess the number between 1 and 10: "))
    if guess == secret_number:
        print("You win!")
        break
    elif guess < secret_number:
        print("Too low!")
    else:
        print("Too high!")
    attempts -= 1

# check if user used up all three attempts and lost
if attempts == 0:
    print("You lose!")

"""30.Write a program that prompts the user to enter their age and then prints out whether they are a child (age 0-12), a teenager (age 13-19), an adult (age 20-59), or a senior (age 60+)

"""

# prompt user to enter their age
age = int(input("Enter your age: "))

# check if age falls into child, teenager, adult, or senior category
if age <= 12:
    print("You are a child.")
elif age <= 19:
    print("You are a teenager.")
elif age <= 59:
    print("You are an adult.")
else:
    print("You are a senior.")



"""31.Create a class called "Person" with properties for "name", "age", and "gender". Create an object of this class and print out its properties.

"""

# Define the Person class
class Person:
    # Constructor method to initialize the name, age, and gender properties
    def __init__(self, name, age, gender):
        self.name = name
        self.age = age
        self.gender = gender

# Create an object of the Person class
person1 = Person("John Doe", 30, "male")

# Print out the properties of the person object
print("Name:", person1.name)
print("Age:", person1.age)
print("Gender:", person1.gender)

"""32. Write a Python class called "Rectangle" with attributes for "width" and "height". Implement methods to calculate the area and perimeter of the rectangle. Create an instance of this class and use it to print out the rectangle's area and perimeter.

"""

# Define the Rectangle class
class Rectangle:
    # Constructor method to initialize the width and height properties
    def __init__(self, width, height):
        self.width = width
        self.height = height

    # Method to calculate the area of the rectangle
    def area(self):
        return self.width * self.height

    # Method to calculate the perimeter of the rectangle
    def perimeter(self):
        return 2 * (self.width + self.height)

# Create an object of the Rectangle class
rect1 = Rectangle(5, 10)

# Print out the area and perimeter of the rectangle object
print("Area:", rect1.area())
print("Perimeter:", rect1.perimeter())

"""33. Write a Python class called "BankAccount" with attributes for "balance" and "interest_rate". Implement methods to deposit and withdraw money from the account, as well as to calculate the interest earned on the balance based on the interest rate. Create an instance of this class and use it to test out the implemented methods for deposit, withdrawal, and interest calculation.

"""

# Define the BankAccount class
class BankAccount:
    # Constructor method to initialize the balance and interest_rate properties
    def __init__(self, balance, interest_rate):
        self.balance = balance
        self.interest_rate = interest_rate

    # Method to deposit money into the account
    def deposit(self, amount):
        self.balance += amount

    # Method to withdraw money from the account
    def withdraw(self, amount):
        self.balance -= amount

    # Method to calculate the interest earned on the balance
    def calculate_interest(self):
        return self.balance * self.interest_rate / 100

# Create an object of the BankAccount class
account1 = BankAccount(1000, 1.5)

# Test out the deposit and withdraw methods
account1.deposit(500)
account1.withdraw(200)

# Test out the calculate_interest method
interest_earned = account1.calculate_interest()

# Print out the balance and interest earned on the account
print("Balance:", account1.balance)
print("Interest earned:", interest_earned)

"""34. Write a Python class called "Animal" with attributes for "name" and "species". Create a subclass of "Animal" called "Dog" with additional attributes for "breed" and "owner". Implement both classes with appropriate methods and constructors to initialise their properties. Create instances of both classes and use them to print out the various properties of the animals and dogs, such as their names, species, breeds, and owners."""

# Define the Animal class
class Animal:
    # Constructor method to initialize the name and species properties
    def __init__(self, name, species):
        self.name = name
        self.species = species

# Define the Dog subclass, which inherits from Animal
class Dog(Animal):
    # Constructor method to initialize the breed and owner properties
    def __init__(self, name, species, breed, owner):
        # Call the parent class's constructor to initialize the name and species properties
        super().__init__(name, species)
        self.breed = breed
        self.owner = owner

# Create an object of the Animal class
animal1 = Animal("Tiger", "Feline")

# Create an object of the Dog class
dog1 = Dog("Max", "Canine", "Labrador Retriever", "John")

# Print out the properties of the animal1 object
print("Animal name:", animal1.name)
print("Animal species:", animal1.species)

# Print out the properties of the dog1 object
print("Dog name:", dog1.name)
print("Dog species:", dog1.species)
print("Dog breed:", dog1.breed)
print("Dog owner:", dog1.owner)

"""35.Create a class called "Car" with properties for "make", "model", and "year". Create a subclass of "Car" called "ElectricCar" with additional properties for "battery_size" and "range". Create objects of both classes and print out their properties.

"""

# Define the Car class
class Car:
    # Constructor method to initialize the make, model, and year properties
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

# Define the ElectricCar subclass, which inherits from Car
class ElectricCar(Car):
    # Constructor method to initialize the battery_size and range properties
    def __init__(self, make, model, year, battery_size, range):
        # Call the parent class's constructor to initialize the make, model, and year properties
        super().__init__(make, model, year)
        self.battery_size = battery_size
        self.range = range

# Create an object of the Car class
car1 = Car("Toyota", "Camry", 2019)

# Create an object of the ElectricCar class
electric_car1 = ElectricCar("Tesla", "Model 3", 2021, 75, 263)

# Print out the properties of the car1 object
print("Car make:", car1.make)
print("Car model:", car1.model)
print("Car year:", car1.year)

# Print out the properties of the electric_car1 object
print("Electric car make:", electric_car1.make)
print("Electric car model:", electric_car1.model)
print("Electric car year:", electric_car1.year)
print("Electric car battery size:", electric_car1.battery_size)
print("Electric car range:", electric_car1.range)

"""36.Create a class called "Student" with properties for "name" and "id". Create a subclass of "Student" called "GraduateStudent" with additional properties for "advisor" and "research_area". Create objects of both classes and print out their properties.

"""

# Define the Student class
class Student:
    # Constructor method to initialize the name and id properties
    def __init__(self, name, id):
        self.name = name
        self.id = id

# Define the GraduateStudent subclass, which inherits from Student
class GraduateStudent(Student):
    # Constructor method to initialize the advisor and research_area properties
    def __init__(self, name, id, advisor, research_area):
        # Call the parent class's constructor to initialize the name and id properties
        super().__init__(name, id)
        self.advisor = advisor
        self.research_area = research_area

# Create an object of the Student class
student1 = Student("John Doe", 12345)

# Create an object of the GraduateStudent class
grad_student1 = GraduateStudent("Jane Smith", 67890, "Dr. Johnson", "Computer Science")

# Print out the properties of the student1 object
print("Student name:", student1.name)
print("Student id:", student1.id)

# Print out the properties of the grad_student1 object
print("Graduate student name:", grad_student1.name)
print("Graduate student id:", grad_student1.id)
print("Graduate student advisor:", grad_student1.advisor)
print("Graduate student research area:", grad_student1.research_area)

"""37. Create a class called "Shape" with methods to calculate the area and perimeter of the shape. Create subclasses of "Shape" for "Rectangle", "Circle", and "Triangle" with their own methods for calculating area and perimeter. Create objects of each class and print out their area and perimeter.

"""

import math

# Define the Shape class
class Shape:
    def calculate_area(self):
        pass

    def calculate_perimeter(self):
        pass

# Define the Rectangle class, which inherits from Shape
class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def calculate_area(self):
        return self.width * self.height

    def calculate_perimeter(self):
        return 2 * (self.width + self.height)

# Define the Circle class, which inherits from Shape
class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def calculate_area(self):
        return math.pi * self.radius ** 2

    def calculate_perimeter(self):
        return 2 * math.pi * self.radius

# Define the Triangle class, which inherits from Shape
class Triangle(Shape):
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def calculate_area(self):
        s = (self.a + self.b + self.c) / 2
        return math.sqrt(s * (s - self.a) * (s - self.b) * (s - self.c))

    def calculate_perimeter(self):
        return self.a + self.b + self.c

# Create objects of each class and print out their area and perimeter
rectangle = Rectangle(5, 3)
print("Rectangle area:", rectangle.calculate_area())
print("Rectangle perimeter:", rectangle.calculate_perimeter())

circle = Circle(4)
print("Circle area:", circle.calculate_area())
print("Circle perimeter:", circle.calculate_perimeter())

triangle = Triangle(3, 4, 5)
print("Triangle area:", triangle.calculate_area())
print("Triangle perimeter:", triangle.calculate_perimeter())

"""38.Create a class called "Employee" with properties for "name", "id", and "salary". Add methods to give the employee a raise and to calculate their annual salary. Create objects of this class and test out the methods.

"""

class Employee:
    def __init__(self, name, id, salary):
        self.name = name
        self.id = id
        self.salary = salary

    def give_raise(self, amount):
        self.salary += amount

    def annual_salary(self):
        return self.salary * 12

# create an employee object
employee1 = Employee("John Doe", 12345, 50000)

# print out the initial salary
print("Initial salary:", employee1.salary)

# give the employee a raise of $1000
employee1.give_raise(1000)

# print out the new salary
print("New salary:", employee1.salary)

# print out the annual salary
print("Annual salary:", employee1.annual_salary())

"""39.Create a class called "Book" with properties for "title", "author", and "publisher". Create a subclass of "Book" called "Ebook" with additional properties for "file_format" and "file_size". Create objects of both classes and print out their properties.

"""

class Book:
    def __init__(self, title, author, publisher):
        self.title = title
        self.author = author
        self.publisher = publisher

class Ebook(Book):
    def __init__(self, title, author, publisher, file_format, file_size):
        super().__init__(title, author, publisher)
        self.file_format = file_format
        self.file_size = file_size

# Create an object of the Book class
book1 = Book("To Kill a Mockingbird", "Harper Lee", "J. B. Lippincott & Co.")

# Create an object of the Ebook class
ebook1 = Ebook("The Hunger Games", "Suzanne Collins", "Scholastic Corporation", "PDF", "2.5 MB")

# Print out the properties of book1
print("Book title:", book1.title)
print("Book author:", book1.author)
print("Book publisher:", book1.publisher)

# Print out the properties of ebook1
print("Ebook title:", ebook1.title)
print("Ebook author:", ebook1.author)
print("Ebook publisher:", ebook1.publisher)
print("Ebook file format:", ebook1.file_format)
print("Ebook file size:", ebook1.file_size)

"""40.Create a class called "Bank" with properties for "name" and "accounts". Add methods to create new accounts, deposit and withdraw money from accounts, and to calculate the total balance of all accounts. Create an object of this class and test out the methods.

"""

class Book:
    def __init__(self, title, author, publisher):
        self.title = title
        self.author = author
        self.publisher = publisher

class Ebook(Book):
    def __init__(self, title, author, publisher, file_format, file_size):
        super().__init__(title, author, publisher)
        self.file_format = file_format
        self.file_size = file_size

# Create an object of the Book class
book1 = Book("To Kill a Mockingbird", "Harper Lee", "J. B. Lippincott & Co.")

# Create an object of the Ebook class
ebook1 = Ebook("The Hunger Games", "Suzanne Collins", "Scholastic Corporation", "PDF", "2.5 MB")

# Print out the properties of book1
print("Book title:", book1.title)
print("Book author:", book1.author)
print("Book publisher:", book1.publisher)

# Print out the properties of ebook1
print("Ebook title:", ebook1.title)
print("Ebook author:", ebook1.author)
print("Ebook publisher:", ebook1.publisher)
print("Ebook file format:", ebook1.file_format)
print("Ebook file size:", ebook1.file_size)





"""41.Can you create a Python program that reads a text file and counts the number of words contained within it? The program should be designed to read the file and break it down into individual words, using spaces, punctuation marks, and other delimiters to separate the words. It should then count the number of words found in the file and display this count as output. The program should be flexible enough to work with different text files and should be able to handle a variety of formatting and punctuation styles."""

# Open the file in read mode
with open("filename.txt", "r") as file:
    # Read the content of the file and split it into words
    words = file.read().split()

# Count the number of words
num_words = len(words)

# Print the number of words in the file
print("Number of words:", num_words)

##NOTE:
#Make sure to replace filename.txt with the name of the text file you want to read.
#This program reads the entire contents of the file, splits it into words using whitespace as the separator,
#counts the number of words, and prints the result.

"""42. Could you help me create a Python program that can find and display the longest word in a text file? The program should be able to read any text file and separate its contents into individual words, taking into account various delimiters like spaces, punctuation marks, and other characters. Then, it should compare the length of each word and determine which one is the longest, and finally, print that word as output. The program should be versatile enough to work with various text files and be able to handle different formatting styles and punctuation.

"""

with open("filename.txt", "r") as file:
    text = file.read()
    words = text.split()

longest_word = max(words, key=len)
print("The longest word is:", longest_word)

"""43.Write a Python program to read a text file and print out the most frequent word(s) in the file.

"""

from collections import Counter

# Open the file and read its contents
with open('filename.txt', 'r') as file:
    text = file.read()

# Remove special characters and split the text into words
words = text.lower().replace('\n', ' ').split()

# Count the frequency of each word using Counter from collections module
word_count = Counter(words)

# Find the most frequent word(s)
most_common = word_count.most_common()

# Get the count of the most frequent word(s)
max_count = most_common[0][1]

# Print out all the words that have the same maximum frequency
print("Most frequent word(s):")
for word, count in most_common:
    if count == max_count:
        print(f"{word}: {count} times")
    else:
        break

"""44. How can you use Python to count the number of rows in a CSV file?

"""

import csv

filename = "example.csv"  # replace with the name of your CSV file

with open(filename, 'r') as csvfile:
    reader = csv.reader(csvfile)
    num_rows = sum(1 for row in reader)

print(f"The number of rows in {filename} is {num_rows}")

"""45. How can you use Python to calculate the average of a specific column in a CSV file?

"""

import csv

filename = "example.csv"  # replace with the name of your CSV file
column_index = 2  # replace with the index of the column you want to calculate the average of

with open(filename, 'r') as csvfile:
    reader = csv.reader(csvfile)
    next(reader)  # skip header row
    values = [float(row[column_index]) for row in reader]

average = sum(values) / len(values)
print(f"The average of column {column_index} in {filename} is {average}")

"""46.Write a Python program to read a JSON file and print out the value of a specified key.

"""

import json

filename = "example.json"  # replace with the name of your JSON file
key = "name"  # replace with the key you want to get the value of

with open(filename, 'r') as jsonfile:
    data = json.load(jsonfile)

value = data[key]
print(f"The value of key {key} in {filename} is {value}")

"""47. Can you provide a Python code snippet to write a list of strings into a text file where each string is written on a new line?

"""

strings = ["Hello", "world", "how", "are", "you"]
filename = "example.txt"  # replace with the name of the text file you want to create

with open(filename, 'w') as textfile:
    for s in strings:
        textfile.write(s + '\n')

"""48. Can you provide a Python code to read a binary file and display the data in hexadecimal format.

"""

filename = "example.bin"  # replace with the name of your binary file

with open(filename, 'rb') as binaryfile:
    binary_data = binaryfile.read()
    hex_data = binascii.hexlify(binary_data).decode()

print(f"The hexadecimal representation of the binary data in {filename} is:\n{hex_data}")

"""49. Can you write a Python code to read a Comma-Separated Values (CSV) file, apply a specific condition to each row, and create a new CSV file that contains only the rows that satisfy the condition? For example, if the CSV file contains information about products and their prices, you may want to create a new CSV file that only includes the products that are within a certain price range. The program should be able to read the CSV file, compare the values in each row to the specified condition, and write the rows that meet the criteria to a new CSV file.

"""

import csv

input_filename = "input.csv"  # replace with the name of your input CSV file
output_filename = "output.csv"  # replace with the name of the output CSV file
condition_column_index = 1  # replace with the index of the column to apply the condition to
condition_value = "true"  # replace with the value that the condition column should have to include the row

with open(input_filename, 'r') as input_file, open(output_filename, 'w', newline='') as output_file:
    reader = csv.reader(input_file)
    writer = csv.writer(output_file)

    for row in reader:
        if row[condition_column_index] == condition_value:
            writer.writerow(row)

"""50.Write a Python program to read a text file, count the frequency of each word, and write the results to a new text file.

"""

input_filename = "input.txt"  # replace with the name of your input text file
output_filename = "output.txt"  # replace with the name of the output text file

# Define a function to count the frequency of each word in a list
def count_word_frequency(words):
    frequency = {}
    for word in words:
        if word in frequency:
            frequency[word] += 1
        else:
            frequency[word] = 1
    return frequency

# Read the input text file and count the frequency of each word
with open(input_filename, 'r') as input_file:
    text = input_file.read()
    words = text.split()
    word_frequency = count_word_frequency(words)

# Write the word frequency data to the output text file
with open(output_filename, 'w') as output_file:
    for word, count in word_frequency.items():
        output_file.write(f"{word}: {count}\n")

"""51.Write a program that prints the first 10 even numbers using a for loop.

"""

# use a for loop to print the first 10 even numbers
for i in range(2, 21, 2):
    print(i)

"""52.Write a program that takes a list of strings and prints out each string in reverse order using a for loop.

"""

# take a list of strings
my_list = ["hello", "world", "python", "programming"]

# use a for loop to print each string in reverse order
for s in my_list:
    print(s[::-1])

"""53.Write a program that prints the multiplication table of a given number using a for loop.

"""

# take input from the user
num = int(input("Enter a number: "))

# use a for loop to iterate from 1 to 10
for i in range(1, 11):
    # calculate the product of num and i
    product = num * i

    # print the result
    print(num, "x", i, "=", product)

"""54.Write a program that takes a list of integers as input and returns the sum of all the numbers in the list using a for loop.

"""

def sum_list(numbers):
    total = 0
    for num in numbers:
        total += num
    return total

# Example usage:
my_list = [1, 2, 3, 4, 5]
print(sum_list(my_list))

"""55.Write a program that prompts the user for a positive integer and then prints out all the prime numbers up to that number using a for loop.

"""

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Prompt user for input
n = int(input("Enter a positive integer: "))

# Loop through all numbers up to n and print prime numbers
for i in range(2, n+1):
    if is_prime(i):
        print(i)

"""56.Write a program that prompts the user to enter a password until the correct password is entered using a while loop.

"""

# Define the correct password
password = "password123"

# Prompt the user to enter a password
user_input = input("Enter password: ")

# Keep prompting until correct password is entered
while user_input != password:
    print("Incorrect password!")
    user_input = input("Enter password: ")

print("Correct password!")

"""57.Write a program that takes a list of strings and prints out each string in reverse order using a while loop.

"""

# Define the list of strings
string_list = ["hello", "world", "python", "programming"]

# Loop through each string in the list and print it in reverse order
for string in string_list:
    index = len(string) - 1
    while index >= 0:
        print(string[index], end="")
        index -= 1
    print()

"""58.Write a program that prompts the user to enter a positive integer and then prints out all the Fibonacci numbers up to that number using a while loop.

"""

# Prompt user for input
n = int(input("Enter a positive integer: "))

# Initialize variables for the first two Fibonacci numbers
fib1 = 0
fib2 = 1

# Print the first Fibonacci number (0)
print(fib1)

# Print the second Fibonacci number (1)
print(fib2)

# Loop through all remaining Fibonacci numbers up to n
while fib2 <= n:
    # Compute the next Fibonacci number and print it
    fib3 = fib1 + fib2
    print(fib3)

    # Update variables for the next iteration
    fib1 = fib2
    fib2 = fib3

"""59.Write a program that takes a list of integers as input and returns the product of all the numbers in the list using a while loop.

"""

# Define the list of integers
int_list = [2, 4, 6, 8, 10]

# Initialize the product variable to 1
product = 1

# Loop through each integer in the list and multiply it with the product variable
index = 0
while index < len(int_list):
    product *= int_list[index]
    index += 1

# Print the final product
print(product)

"""60.Write a program that prompts the user to enter a positive integer and then prints out the factorial of that number using a while loop.

"""

# Prompt user for input
n = int(input("Enter a positive integer: "))

# Initialize the factorial variable to 1
factorial = 1

# Loop through all integers from 1 to n
i = 1
while i <= n:
    # Multiply the current value of the factorial variable with i
    factorial *= i

    # Update the loop counter
    i += 1

# Print the final factorial value
print(factorial)



"""61.Write a program that spawns two threads. One thread should print even numbers between 0 and 10, and the other thread should print odd numbers between 1 and 9."""

import threading

def print_even():
    for i in range(0, 11, 2):
        print(i)

def print_odd():
    for i in range(1, 10, 2):
        print(i)

# create threads
t1 = threading.Thread(target=print_even)
t2 = threading.Thread(target=print_odd)

# start threads
t1.start()
t2.start()

# wait for threads to finish
t1.join()
t2.join()



"""62.Write a program that generates a list of random numbers and sorts them using multithreading. Use two threads to sort the first half and the second half of the list in parallel."""

import threading
import random

# generate a list of random numbers
my_list = [random.randint(1, 100) for _ in range(10)]
print("Original List:", my_list)

# define the function to sort the list
def sort_list(start, end):
    my_list[start:end] = sorted(my_list[start:end])

# create threads for sorting
t1 = threading.Thread(target=sort_list, args=(0, len(my_list)//2))
t2 = threading.Thread(target=sort_list, args=(len(my_list)//2, len(my_list)))

# start the threads
t1.start()
t2.start()

# wait for threads to finish
t1.join()
t2.join()

# merge the sorted sublists
sorted_list = sorted(my_list)

print("Sorted List:", sorted_list)



"""63.Write a program that simulates a bank account transaction. The program should create two threads, one for a deposit and one for a withdrawal. The deposit thread should add $100 to the account, and the withdrawal thread should withdraw $50 from the account. Run the program for 10 iterations.

"""

import threading

balance = 0
lock = threading.Lock()

def deposit():
    global balance
    for i in range(10):
        lock.acquire()
        balance += 100
        print("Deposited $100, balance is now $" + str(balance))
        lock.release()

def withdraw():
    global balance
    for i in range(10):
        lock.acquire()
        balance -= 50
        print("Withdrawn $50, balance is now $" + str(balance))
        lock.release()

deposit_thread = threading.Thread(target=deposit)
withdraw_thread = threading.Thread(target=withdraw)

deposit_thread.start()
withdraw_thread.start()

deposit_thread.join()
withdraw_thread.join()



"""64.Write a Python program that creates a thread to print out the current date and time every 5 seconds. The program should continue running until the user presses the 'q' key."""

import threading
import time

def print_time():
    while True:
        print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
        time.sleep(5)

t = threading.Thread(target=print_time)
t.start()

while True:
    if input() == 'q':
        break



"""65.Write a Python program that creates two threads. Each thread should print out the numbers from 1 to 10. The two threads should run concurrently and print out the numbers in an interleaved fashion."""

import threading

def print_numbers(start, end):
    for i in range(start, end+1):
        print(i)

# create two threads
thread1 = threading.Thread(target=print_numbers, args=(1, 10))
thread2 = threading.Thread(target=print_numbers, args=(1, 10))

# start the threads
thread1.start()
thread2.start()

# wait for the threads to finish
thread1.join()
thread2.join()



"""66.Write a Python program to create a shared variable between two threads and increment its value in each thread."""

import threading

shared_variable = 0
lock = threading.Lock()

def increment_variable():
    global shared_variable
    lock.acquire()
    shared_variable += 1
    lock.release()

num1 = threading.Thread(target=increment_variable)
num2 = threading.Thread(target=increment_variable)

num1.start()
num2.start()

num1.join()
num2.join()

print("Shared variable value: ", shared_variable)



"""67.Here's a Python program that creates a thread to count down from 5 to 0 and prints "Blastoff!" when the count reaches 0:"""

import threading as s
import time

def countdown():
  for i in range(5, 0, -1):
    print(i)
    time.sleep(1)
  print("Blastoff!")

threada = s.Thread(target=countdown())
threada.start()



"""68.Write a program that creates a thread to print the Fibonacci sequence up to a certain number n. The main thread should prompt the user for the value of n."""

import threading

def fib(n):
    """
    Print the Fibonacci sequence up to n.
    """
    a, b = 0, 1
    while a <= n:
        print(a, end=' ')
        a, b = b, a+b

# Prompt the user for the value of n
n = int(input("Enter a number: "))

# Create a thread to print the Fibonacci sequence
t = threading.Thread(target=fib, args=(n,))
t.start()

# Wait for the thread to finish before exiting
t.join()

"""69.Write a program that creates two threads to add and subtract numbers from a shared variable. The shared variable should start at 0, and each thread should perform 10 iterations of adding or subtracting a random integer between 1 and 10. The program should print the final value of the shared variable."""

import threading
import random
import time

class AddThread(threading.Thread):
    def __init__(self, shared_var):
        super().__init__()
        self.shared_var = shared_var

    def run(self):
        for i in range(10):
            num = random.randint(1, 10)
            self.shared_var += num
            print("Added", num, "to shared variable")
            time.sleep(0.1)

class SubtractThread(threading.Thread):
    def __init__(self, shared_var):
        super().__init__()
        self.shared_var = shared_var

    def run(self):
        for i in range(10):
            num = random.randint(1, 10)
            self.shared_var -= num
            print("Subtracted", num, "from shared variable")
            time.sleep(0.1)

shared_var = 0
add_thread = AddThread(shared_var)
subtract_thread = SubtractThread(shared_var)

add_thread.start()
subtract_thread.start()

add_thread.join()
subtract_thread.join()

print("Final value of shared variable is", shared_var)



"""70.Write a program that creates a thread to calculate the sum of the numbers from 1 to 100 and prints the result."""

import threading

def sum_numbers():
    result = sum(range(1, 101))
    print("The sum of the numbers from 1 to 100 is:", result)

thread = threading.Thread(target=sum_numbers)
thread.start()
thread.join()

"""71.Write a Python program to create two processes that print out the numbers from 1 to 10 simultaneously."""

from multiprocessing import Process

def print_numbers(start, end):
    for i in range(start, end+1):
        print(i)

if __name__ == '__main__':
    p1 = Process(target=print_numbers, args=(1, 5))
    p2 = Process(target=print_numbers, args=(6, 10))

    p1.start()


    p1.join()

    p2.start()
    p2.join()



"""72.Write a Python program that creates four processes and computes the sum of the first 1000 integers using multiprocessing"""

from multiprocessing import Process, Value

def compute_sum(start, end, total):
    for i in range(start, end+1):
        with total.get_lock():
            total.value += i

if __name__ == '__main__':
    total = Value('i', 0)

    p1 = Process(target=compute_sum, args=(1, 250, total))
    p2 = Process(target=compute_sum, args=(251, 500, total))
    p3 = Process(target=compute_sum, args=(501, 750, total))
    p4 = Process(target=compute_sum, args=(751, 1000, total))

    p1.start()
    p2.start()
    p3.start()
    p4.start()

    p1.join()
    p2.join()
    p3.join()
    p4.join()

    print('Total:', total.value)



"""73.Write a Python program that creates two processes and communicates between them using a Queue. The first process should send a list of numbers to the second process, which should calculate the sum of the numbers and send it back to the first process."""

from multiprocessing import Process, Queue

def calculate_sum(numbers, q):
    """
    This function takes a list of numbers and calculates the sum of them.
    The result is put into a queue to be returned to the main process.
    """
    result = sum(numbers)
    q.put(result)

if __name__ == '__main__':
    # Define the list of numbers to be summed
    numbers = [1, 2, 3, 4, 5]

    # Create a queue to communicate between processes
    q = Queue()

    # Create a process to calculate the sum of the numbers
    p = Process(target=calculate_sum, args=(numbers, q))
    p.start()

    # Wait for the result to be put in the queue and retrieve it
    result = q.get()

    # Print the result
    print(f"The sum of the numbers {numbers} is {result}.")



"""74.Write a program to find the maximum number in a list of lists using multiprocessing."""

import multiprocessing

def find_max(nums):
    return max(nums)

if __name__ == '__main__':
    nums = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    with multiprocessing.Pool(processes=3) as pool:
        result = pool.map(find_max, nums)
    print(max(result))



"""75.Write a Python program that uses the Pool class from the multiprocessing

*   List item
*   List item

module to calculate the squares of a list of integers.
"""

import multiprocessing

def square(x):
    return x ** 2

if __name__ == '__main__':
    with multiprocessing.Pool(processes=4) as pool:
        numbers = [1, 2, 3, 4, 5]
        result = pool.map(square, numbers)
        print(result)



"""76.How do you create a new process using the multiprocessing module in Python?"""

import multiprocessing

def my_function():
    print("This is a child process.")

if __name__ == '__main__':
    p = multiprocessing.Process(target=my_function)
    p.start()



"""77.How do you use a Pool to execute a function with multiple arguments in parallel?"""

import multiprocessing

def my_function(num1, num2):
    return num1 * num2

if __name__ == '__main__':
    with multiprocessing.Pool(processes=2) as pool:
        results = pool.starmap(my_function, [(2, 3), (4, 5)])
    print(results)



"""78.Write a Python program to calculate the sum of squares of numbers in a list using multiprocessing."""

import multiprocessing

def square_sum(numbers, result):
    """Calculate the sum of squares of numbers and store the result in the given shared array."""
    total = 0
    for num in numbers:
        total += num**2
    result.value = total

if __name__ == "__main__":
    nums = [1, 2, 3, 4, 5]
    result = multiprocessing.Value('i')  # shared integer value
    p = multiprocessing.Process(target=square_sum, args=(nums, result))
    p.start()
    p.join()
    print(f"Sum of squares of {nums} is {result.value}")



"""79.Write a Python program that uses the multiprocessing module to calculate the sum of a large list of integers."""

import multiprocessing
def sum_worker(data_chunk):
    return sum(data_chunk)
def main():
    data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 100000
    pool = multiprocessing.Pool(processes=4)
    chunksize = len(data) // 4
    chunks = [data[i:i+chunksize] for i in range(0, len(data), chunksize)]
    results = pool.map(sum_worker, chunks)
    pool.close()
    pool.join()
    total = sum(results)
    print(total)
if __name__ == "__main__":
    main()



"""80.Write a Python program that uses the multiprocessing module to parallelize the computation of the factorial of a number."""

import multiprocessing
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
def factorial_worker(n):
    return factorial(n)
def main():
    n = 10
    pool = multiprocessing.Pool(processes=4)
    results = pool.map(factorial_worker, range(1, n+1))
    pool.close()
    pool.join()
    print(f"The factorials of the numbers 1 to {n} are: {results}")
if __name__ == "__main__":
    main()



"""81. Write a Python program that prompts the user for two integers and divides the first integer by the second integer. If the either variable are none integer then print the value error and  second integer is zero, catch the ZeroDivisionError and print an error message to the user.



"""

while True:
    try:
        x = int(input("Enter the first integer: "))
        y = int(input("Enter the second integer: "))
        result = x / y
        print("Result: ", result)
        break
    except ValueError:
        print("Please enter integers only.")
    except ZeroDivisionError:
        print("Error: division by zero. Please enter a non-zero value for the second integer.")



"""82.Write a Python program that prompts the user for a password and checks whether the password meets certain criteria (e.g., at least 8 characters, contains at least one uppercase letter, etc.). If the password does not meet the criteria, raise a custom exception called PasswordError with a custom error message.


"""

class PasswordError(Exception):
    pass

def check_password(password):
    # Check password criteria
    if len(password) < 8:
        raise PasswordError("Error: password must be at least 8 characters long.")
    elif not any(char.isupper() for char in password):
        raise PasswordError("Error: password must contain at least one uppercase letter.")
    elif not any(char.isdigit() for char in password):
        raise PasswordError("Error: password must contain at least one digit.")
    elif not any(char in ['$', '#', '@'] for char in password):
        raise PasswordError("Error: password must contain at least one of the following special characters: $ # @")
    else:
        print("Password is valid.")

# Prompt user for password
password = input("Enter a password: ")

# Check password
try:
    check_password(password)
except PasswordError as e:
    print(e)



"""83.Write a Python program that prompts the user for a number and calculates the square root of the number using the math.sqrt() function. If the number is negative, raise a ValueError with a custom error message.

"""

while True:
    try:
        # Prompt user for list of strings
        string_list = input("Enter a list of strings separated by commas: ").split(",")

        # Sort list in alphabetical order
        sorted_list = sorted(string_list)

        # Check if any string contains non-alphabetic characters
        for string in sorted_list:
            if not string.isalpha():
                raise TypeError("Error: list contains non-alphabetic characters.")

        # Print sorted list
        print("Sorted list:", sorted_list)
        break
    except TypeError as e:
        print(e)



"""84.Write a Python program that prompts the user for a number and calculates the square root of the number using the math.sqrt() function. If the number is negative, raise a ValueError with a custom error message."""

import math

while True:
    try:
        # Prompt user for number
        num = float(input("Enter a number: "))

        # Check if number is negative
        if num < 0:
            raise ValueError("Error: number cannot be negative.")

        # Calculate square root
        result = math.sqrt(num)
        print("The square root of", num, "is", result)
        break
    except ValueError as e:
        print(e)



"""85.Write a Python program that prompts the user for a list of integers and calculates the average of the list. If the list is empty, raise a ValueError with a custom error message.

"""

try:
    # Prompt user for a list of integers
    num_list = [int(num) for num in input("Enter a list of integers (separated by spaces): ").split()]

    # Calculate the average of the list
    avg = sum(num_list) / len(num_list)
    print("Average of the list:", avg)

    # Raise a ValueError if the list is empty
    if not num_list:
        raise ValueError("List is empty")
except ValueError as e:
    print("Error:", e)



"""86.Write a function that takes a string as input and returns the number of vowels in the string. If the input is not a string, raise a TypeError with a custom error message.

"""

def count_vowels(string):
    try:
        # Check if input is a string
        if not isinstance(string, str):
            raise TypeError("Input must be a string")

        # Count and return the number of vowels in the string
        vowels = "aeiouAEIOU"
        return sum([1 for char in string if char in vowels])
    except TypeError as e:
        print("Error:", e)

count_vowels(4)

count_vowels("aieoujdnj")

count_vowels("this is a function")



"""87.write a python program how to handle simple runtime error?"""

a = [1, 2, 3]
try:
    print ("Second element = %d" %(a[1]))
    # Throws error since there are only 3 elements in array
    print ("Fourth element = %d" %(a[3]))
except:
    print ("An error occurred")

"""88.write a program how to handle  multiple errors with one
answer:# Program to handle multiple errors with one
"""

def fun(a):
	if a < 4:
		# throws ZeroDivisionError for a = 3
		b = a/(a-3)
	# throws NameError if a >= 4
	print("Value of b = ", b)

try:
	fun(3)
	fun(5)
# note that braces () are necessary here for
# multiple exceptions
except ZeroDivisionError:
	print("ZeroDivisionError Occurred and Handled")
except NameError:
	print("NameError Occurred and Handled")



"""89. write a program to print the reciprocal of even numbers
note:we might want to run a certain block of code if the code block inside try runs without any errors.
For these cases, you can use the optional else keyword with the try statement.
"""

try:
    num = int(input("Enter a number: "))
    assert num % 2 == 0
except:
    print("Not an even number!")
else:
    reciprocal = 1/num
    print(reciprocal)



"""90.How to handle exceptions using the try, except, and finally statements write code"""

try:
    # Ask the user to enter a number
    num = int(input("Enter a number: "))

    # Divide the number by 2
    result = 2 / num

    # Print the result
    print("Result:", result)
except ValueError:
    # Handle the case where the user did not enter a valid number
    print("Error: You must enter a valid number")
except ZeroDivisionError:
    # Handle the case where the user entered 0 as the number
    print("Error: You cannot divide by zero")
finally:
    # Clean up resources or run some final code
    print("Thank you for using this program!")





"""**91.Write a Python program to create a MySQL database and a table.**

**solution:-**


"""

import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="yourusername",
  password="yourpassword"
)
mycursor = mydb.cursor()
mycursor.execute("CREATE DATABASE mydatabase")
mycursor.execute("CREATE TABLE customers (name VARCHAR(255), address VARCHAR(255))")



"""**92. Write a Python program to insert data into a MySQL table.**

**solution:-**

"""

import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="yourusername",
  password="yourpassword",
  database="mydatabase"
)
mycursor = mydb.cursor()
sql = "INSERT INTO customers (name, address) VALUES (%s, %s)"
val = ("John", "Highway 21")
mycursor.execute(sql, val)
mydb.commit()
print(mycursor.rowcount, "record inserted.")



"""
**93. Write a Python program to create an index on a MySQL table.**

**solution:-**

"""

import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="yourusername",
  password="yourpassword",
  database="mydatabase"
)
mycursor = mydb.cursor()
mycursor.execute("CREATE INDEX idx_name ON customers (name)")



"""**94. Write a Python program to join two tables in MySQL.**

**solution:-**


"""

import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="yourusername",
  password="yourpassword",
  database="mydatabase"
)
mycursor = mydb.cursor()
mycursor.execute("SELECT customers.name, orders.product_name FROM customers INNER JOIN orders ON customers.id = orders.customer_id")
myresult = mycursor.fetchall()
for x in myresult:
  print(x)



"""**95. Write a Python program to handle MySQL errors using exception
handling.**

**solution:-**


"""

import mysql.connector
try:
  mydb = mysql.connector.connect(
    host="localhost",
    user="yourusername",
    password="yourpassword",
    database="mydatabase"
  )
except mysql.connector.Error as err:
  print("Something went wrong: {}".format(err))
else:
  mycursor = mydb.cursor()
  mycursor.execute("SELECT * FROM customers")
  myresult = mycursor.fetchall()
  for x in myresult:
    print(x)
finally:
  mydb.close()



"""**96. Write a Python program to connect to a MongoDB database and insert
data.**

**solution:-**


"""

import pymongo
myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["mydatabase"]
mycol = mydb["customers"]
mydict = { "name": "John", "address": "Highway 37" }
x = mycol.insert_one(mydict)
print(x.inserted_id)



"""**97. Write a Python program to update data in a MongoDB database.**

**solution:-**


"""

import pymongo
myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["mydatabase"]
mycol = mydb["customers"]
myquery = { "address": "Highway 37" }
newvalues = { "$set": { "address": "Park Lane 38" } }
mycol.update_many(myquery, newvalues)
print("Documents updated:", mycol.modified_count)



"""**98. Write a Python program to handle MongoDB errors using exception
handling.**

**solution:-**


"""

import pymongo
try:
  myclient = pymongo.MongoClient("mongodb://localhost:27017/")
  mydb = myclient["mydatabase"]
  mycol = mydb["customers"]
except pymongo.errors.ConnectionFailure as err:
  print("Could not connect to MongoDB: {}".format(err))
else:
  mydict = { "name": "John", "address": "Highway 37" }
  x = mycol.insert_one(mydict)
  print(x.inserted_id)
finally:
  myclient.close()



"""**99. Write a Python program to query a MongoDB database using
aggregation.**

**solution:-**


"""

import pymongo
myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["mydatabase"]
mycol = mydb["customers"]
pipeline = [
  { "$match": { "address": "Highway 37" } },
  { "$group": { "_id": "$name", "count": { "$sum": 1 } } }
]
result = mycol.aggregate(pipeline)
for x in result:
  print(x)



"""**100. Write a Python program to perform a text search on a MongoDB
database.**

**solution:-**

"""

import pymongo
myclient = pymongo.MongoClient("mongodb://localhost:27017/")
mydb = myclient["mydatabase"]
mycol = mydb["customers"]
myquery = { "$text": { "$search": "apple" } }
mydoc = mycol.find(myquery)
for x in mydoc:
  print(x)





"""101.Create a Flask application that displays "Hello, World!" on the homepage."""

from flask import Flask
app = Flask(_name_)
@app.route("/")
def hello():
    return "Hello, World!"
if _name_ == "_main_":
    app.run()



"""102. Write a Flask route that takes a name parameter and returns "Hello, [name]!" as plain text."""

from flask import Flask
app = Flask(__name__)
@app.route("/hello/<name>")
def hello(name):
    return f"Hello, {name}!"
if __name__ == "__main__":
    app.run()



"""103.  Write a Flask route that takes a number parameter and returns the square of that number as plain text."""

from flask import Flask
app = Flask(__name__)
@app.route("/square/<int:num>")
def square(num):
    return str(num**2)
if __name__ == "__main__":
    app.run()



"""104.  Write a Flask route that displays a simple HTML form that asks for a name and returns "Hello, [name]!" when submitted."""

from flask import Flask, request, render_template
app = Flask(__name__)
@app.route("/", methods=["GET", "POST"])
def hello():
    if request.method == "POST":
        name = request.form["name"]
        return f"Hello, {name}!"
    else:
        return render_template("index.html")
if __name__ == "__main__":
    app.run()

''' The corresponding index.html file should contain the following:
<!doctype html>
<html>
  <body>
    <form method="POST">
      <label for="name">Name:</label>
      <input type="text" id="name" name="name">
      <input type="submit" value="Submit">
    </form>
  </body>
</html>'''



"""105.  Write a Flask route that displays a list of names in an HTML unordered list."""

from flask import Flask, render_template
app = Flask(__name__)
@app.route("/names")
def names():
    names = [("Alice", 25), ("Bob", 30), ("Charlie", 35)]
    return render_template("names.html", names=names)
if __name__ == "__main__":
    app.run()
'''The corresponding names.html file should contain the following:
<!doctype html>
<html>
  <body>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Age</th>
        </tr>
      </thead>
      <tbody>
        {% for name in names %}
          <tr>
            <td>{{ name[0] }}</td>
            <td>{{ name[1] }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>'''



"""106.  Write a Flask route that displays a list of names in a table."""

from flask import Flask, render_template
app = Flask(__name__)
@app.route("/names")
def names():
    names = ["Alice", "Bob", "Charlie"]
    return render_template("names.html", names=names)
if __name__ == "__main__":
    app.run()
''' The corresponding names.html file should contain the following:
<!doctype html>
<html>
  <body>
    <form method="POST">
      <label for="name">Name:</label>
      <select id="name" name="name">
        {% for name in names %}
          <option value="{{ name }}">{{ name }}</option>
        {% endfor %}
      </select>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>'''



"""107.  Write a Flask route that displays a list of names in a dropdown menu."""

from flask import Flask, render_template
app = Flask(__name__)
@app.route("/names")
def names():
    names = ["Alice", "Bob", "Charlie"]
    return render_template("names.html", names=names)
if __name__ == "__main__":
    app.run()
''' The corresponding names.html file should contain the following:
<!doctype html>
<html>
  <body>
    <form method="POST">
      <label for="name">Name:</label>
      <select id="name" name="name">
        {% for name in names %}
          <option value="{{ name }}">{{ name }}</option>
        {% endfor %}
      </select>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>'''



"""108.  Write a Flask route that receives data through a POST request and returns the data in JSON format."""

from flask import Flask, request, jsonify
app = Flask(__name__)
@app.route("/data", methods=["POST"])
def data():
    data = request.get_json()
    return jsonify(data)
if __name__ == "__main__":
    app.run()



"""109.  Write a Flask route that receives data through a POST request and returns the data in JSON format."""

from flask import Flask, send_from_directory
app = Flask(__name__)
@app.route("/static/<path:filename>")
def static_file(filename):
    return send_from_directory("static", filename)
if __name__ == "__main__":
    app.run()



"""110.  Write a Flask route that redirects the user to a different URL."""

from flask import Flask, redirect
app = Flask(__name__)
@app.route("/")
def index():
    return redirect("/hello")
@app.route("/hello")
def hello():
    return "Hello, World!"
if __name__ == "__main__":
    app.run()

